#cloud-config
users:
  - name: user
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO8qj4Ss6P9LpZR7tAkj6osCwVWnE+krY8bzRttJ9pnj user
chpasswd:
  expire: False
  ssh_pwauth: False

packages:
  - docker.io

runcmd:
 - /usr/bin/docker pull nginxdemos/hello
 - /usr/bin/docker run -d -p 80:80 --restart=always nginxdemos/hello
