#cloud-config
users:
  - name: user
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO8qj4Ss6P9LpZR7tAkj6osCwVWnE+krY8bzRttJ9pnj user
chpasswd:
  expire: False
  ssh_pwauth: False

write_files:
  - content: |
      ---
      version: "2.1"
      services:
        unifi-controller:
          image: lscr.io/linuxserver/unifi-controller:latest
          container_name: unifi-controller
          environment:
            - PUID=1000
            - PGID=1000
            - MEM_LIMIT=1024 #optional
            - MEM_STARTUP=1024 #optional
          volumes:
            - /opt/unifi/config:/config
          ports:
            - 8443:8443
            - 3478:3478/udp
            - 10001:10001/udp
            - 8080:8080
            - 1900:1900/udp #optional
            - 8843:8843 #optional
            - 8880:8880 #optional
            - 6789:6789 #optional
            - 5514:5514/udp #optional
          restart: unless-stopped
    path: /root/unifi-controller.yaml

packages:
  - docker.io
  - docker-compose

runcmd:
 - /bin/mkdir -p /opt/unifi/config
 - /usr/bin/docker-compose -f /root/unifi-controller.yaml up -d
