#cloud-config
users:
  - name: user
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO8qj4Ss6P9LpZR7tAkj6osCwVWnE+krY8bzRttJ9pnj user
  - name: demo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFlLaITnQwVL0gi3HB6luf+4GTYeICJZVyxVzdLGam4u demo
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFO2PrFjrNuo945fdG1kKwuQplslmYPh6yjQuO0BCSD/ demo2
chpasswd:
  expire: False
  ssh_pwauth: False
